version: "3"
services:
  nuxt:
    build: .
    container_name: nuxt_demo
    image: nuxt_demo
    restart: always
    ports:
      - "3000:3000"
    command: "yarn start"
    environment:
      API_URL: ""
    network_mode: bridge
